import Head from "next/head";
import Link from "next/link";
import React from "react";
import Footer from "./Footer";
import Header from "./Header";

const Layout = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title ? title + "-Door-Next-Store" : "Door-Next-Store"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main layout section */}
      <div className="flex min-h-screen flex-col justify-between text-center">
        <header className="">{/* <Header /> */}</header>
        <main>{children}</main>
        <footer>{/* <Footer /> */}</footer>
      </div>
    </div>
  );
};

export default Layout;
