const data = {
  products: [
    {
      name: "Denim",
      slug: "Denim-Item",
      category: "Pants",
      image: "/Images/denim.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "Denim Collections that will amaze you.",
      isFeatured: true,
      banner: "/images/banner1.jpg",
    },
    {
      name: "Denim Short",
      slug: "Denim-Short",
      category: "Pants",
      image: "/Images/DenimShort.jfif",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "Popular denim shorts. Wear it with comfort",
      isFeatured: true,
      banner: "/images/banner2.jpg",
    },
    {
      name: "Fisherman Rib",
      slug: "rib",
      category: "Sweater",
      image: "/Images/fishermanRib.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "Raymond always gives the best product. Try it now.",
    },
    {
      name: "Hoodies",
      slug: "hoodies",
      category: "Sweater",
      image: "/images/hoodies.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking Hoodies. Winter best hoodies collection.",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/Images/jeans.jfif",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "Popular pants. Wearing those will make you feel premium.",
    },
    {
      name: "Polo shirt",
      slug: "polo-shirts",
      category: "T-shirt",
      image: "/Images/polo-shirt.jpg",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "Collections that will amaze you.",
    },
  ],
};

export default data;
